NPC:
  BlomsterMenu: "52"
  BlomsterByenMenu: "53"


Blomster:
  regions:
    - "vvf"
    - "flower"
  chat-prefix: "&8&l[ &6&lBLOMSTER &8&l]"
  chance: 1 # 1 = 0.1% (out of 1000)
  toolName: "&bBlomster Hakke"
  toolPrize: 5000
  gui:
    name: "&8&l[ &6&lBLOMSTER &8&l]"