NPC:
  BlomsterMenu: "20"
  BlomsterByenMenu: "35"


Blomster:
  regions:
    - "vvf"
    - "flower"
  chat-prefix: "&8&l[ &6&lBLOMSTER &8&l]"
  chance: 1
  toolName: "&bBlomster Hakke"
  toolPrize: 5000
  gui:
    name: "&8&l[ &6&lBLOMSTER &8&l]"